### ISSUE TITLE
Using the callbacks is unhandy

### ISSUE THREAD

**Issue by Fuzzyma** [wout/svg.draggable.js#19]
I realized that just passing a function to a variable which is called at the right place doesn't work that well.
You can't bind multiple functions as callback and using closure syntax is impossible too.
Why not trigger an event instead? Binding to events is already supported from the lib so why not triggering events?
You can do something like this after all:
   
    element.node.dispatchEvent(new CustomEvent('dragmove', {detail:{x:ev.pageX, y:ev.pageY}}));

Now everyone could bind functions to this event using `element.on()`.
That would be really great!

Thank you for this great lib and this cool plugin!

**Comment by IonicaBizau** [comment]
We fixed this issue at @jillix, in this fork: https://github.com/jillix/svg.draggable.js

@wout The fork includes other changes, too. However, should we consider making a pull request with them? If not, we will maintain our fork of this great project. :smile:
