### ISSUE TITLE
Prevent click propagating on dragend

### ISSUE THREAD

**Issue by MrHaroldA** [wout/svg.draggable.js#22]
I can't seem to stop the click event from propagating into the object I just dragged. "event.stopPropagation();" in the dragend callback didn't do the trick, and looking into the svg.draggable.js source didn't give me any pointers either.

How do I prevent the click from propagating?

**Comment by Fuzzyma** [comment]
You want to prevent the mousedown event?
Use the `beforedrag`-event:

    el.on('beforedrag', function(e){
        el.detail.event.stopPropagation();
    })

**Comment by chuve** [comment]
Thanks! But small typo:
```javascript
el.on('beforedrag', function(e){
    e.detail.event.stopPropagation();
})
```

**Comment by Fuzzyma** [comment]
Please read through this: #352

**Comment by maxailloud** [comment]
Did dosmething change on that side?
Asking because I am trying to do the exact same thing and it is not working.
The click event still comes up after the `dragend` event.

**Comment by Fuzzyma** [comment]
Well only the mousedown is stopped. Not the mouseup.

**Comment by maxailloud** [comment]
Yeah I was able to see that.
At the end i will have to use a flag to know if i was dragging or not in the click method. No toher way as nothing seems to work to prevent the click event at the end of the drag.

**Comment by maxailloud** [comment]
Well at the end it looks impossible to do as all custom events provided by the plugin are fired even when i am just clicking on my element. So basically I will need to redo all the dragging detection to know if I am in the case of a drag or just a click.
Not really convenient but no other choices if I want to prevent the click at the `dragend` event.

**Comment by maxailloud** [comment]
That's my point I want the dragging but I don't want the click event that goes with it after.
My element is draggable and has a click event bind to it, but I don't want both at the same time.

**Comment by Fuzzyma** [comment]
Well - a click consists of a mousedown and a mouseup. There is nothing you can do about that.
If you only click, the element wont be dragged anyway. If you rely on the drag events, you can check if the element has moved.

**Comment by maxailloud** [comment]
Oh yeah i got that, and nothing wrong with the plugin let's say I was just expecting a system that prevent the event `dragmove` to be fire if no move has been done.

**Comment by merraysy** [comment]
@maxailloud What did you end up doing?

**Comment by github-yd** [comment]
I ended up with 2 options, both works but none is perfect:

1. set a flag in `dragmove` event handler, and in `dragend` event handler (it'll be called even if you just clicked!) check if we really dragged, if yes record the `dragend` event time. Then in click event simply check there is a recent (e.g. 100ms) `dragend` event. If yes just ignore this click. remember to reset your flag in `dragend` event handler. This is more cumbersome in code, but at least more intuitive for the user.

2. use a modifier key for dragging, check the event's modifier key in `dragmove` event handler, only drag when the modifier key is pressed down. Simply ignore the click if a modifier key is pressed. This is slightly simpler than option 1, but at the expense of user education / instruction.

I'd love to know if there is any better option available.

**Comment by merraysy** [comment]
@dany-nonstop Sure there are better options, I ended up detecting movement, After all that's what differentiates Dragging from Clicking.

**Comment by Fuzzyma** [comment]
The last commit adds the logic to only fire a dragmove when the element actually moved. I dont know if it will help with your problem though
