### ISSUE TITLE
fix draggin scaled elements

### ISSUE THREAD

**Issue by incre77** [wout/svg.draggable.js#23]
I added this modification to these lines: 88, 89

x = element.startPosition.x + ((delta.x/ element.trans.scaleX) * Math.cos(rotation) + delta.y * Math.sin(rotation))  / element.startPosition.zoom

y = element.startPosition.y + ((delta.y/ element.trans.scaleY) * Math.cos(rotation) + delta.x * Math.sin(-rotation)) / element.startPosition.zoom

**Comment by IonicaBizau** [comment]
I fixed this in @jillix's fork: https://github.com/jillix/svg.draggable.js

**Comment by Fuzzyma** [comment]
fixed in version 2 (also for all other transformations)
