### ISSUE TITLE
Enhancement Request - Add touch events

### ISSUE THREAD

**Issue by ghost23** [wout/svg.draggable.js#24]
Hi,

it would be nice to have this working on tablets/phones, too. So touch event support would be great.

**Comment by IonicaBizau** [comment]
I have just fixed this in the @jillix's fork: https://github.com/jillix/svg.draggable.js

**Comment by raks437** [comment]
@IonicaBizau: how are you getting the end position when touchleave ? maybe I've been thinking over the start and end position. here - https://github.com/raks437/svg.draggable.js

**Comment by IonicaBizau** [comment]
Is it needed?

Here is the `delta` calculations on `dragEnd`: https://github.com/jillix/svg.draggable.js/blob/8143eb038bae846ef25409e8872c5f0b68b48e51/svg.draggable.js#L157-L161

**Comment by IonicaBizau** [comment]
(parts of code are taken from the pull request you made)

**Comment by raks437** [comment]
Well my point is are you not calculating the `delta` on `drag-end` for touch event as in https://github.com/jillix/svg.draggable.js/blob/8143eb038bae846ef25409e8872c5f0b68b48e51/svg.draggable.js#L101-L102

**Comment by IonicaBizau** [comment]
No,  because it just works. Is there a weird behavior because of this?

**Comment by raks437** [comment]
well, when I was coding for my requirement..I was primarily testing it on chrome browser's built-in emulator and finally tested on other devices. So I'm not sure if that makes a difference. Can you please test yours in both cases and see if that makes any difference.

**Comment by IonicaBizau** [comment]
> I was primarily testing it on chrome browser's built-in emulator 

Me too, but only in emulator... I don't have any *touch* devices. :smile:

**Comment by raks437** [comment]
ok..I have access to many touch devices and I can arrange the testing to be done..let me know if you'd want it to be tested..

**Comment by IonicaBizau** [comment]
@raks437 If you want to contribute to our fork, make a pull request, I will review and merge if it's useful. :smile: Thanks!

**Comment by raks437** [comment]
Hi All,
I've tested my fork: https://github.com/raks437/svg.draggable.js on iPad4/iOS 8.1.1 && Samsung Galaxy Note 10.1 and its seems to work good.

**Comment by IonicaBizau** [comment]
Can you test the @jillix fork too? :smile: 
https://github.com/jillix/svg.draggable.js

**Comment by raks437** [comment]
I just did. 
Drag is working on Galaxy Note but the events `dragstart`, `dragmove` & `dragend`. I could not test for `beforedrag`.
IPad Air or iPad4 drag not working.

**Comment by IonicaBizau** [comment]
Then I'd be happy if you contributed there with a PR.

**Comment by rajkaran** [comment]
Hi @raks437,

I have used your fork and it's working fine, but for some weird reason click event has stopped working on phones and ipad...

**Comment by rajkaran** [comment]
Hey raks437,

The touch event isn't working on iPhones. I don't have an iPhone personally but i have tested my app on my friends iPhone5, iPhone5s and iPhone6 plus...

I couldn't find any online simulator which can help me in narrow down the issue... moreover I don't even have mac book.

I do have ipad4 and your fork actually works on it....

**Comment by Quazistax** [comment]
Hi rajkaran, 

[bubenshchykov fork](https://github.com/bubenshchykov/svg.draggable.js/blob/master/svg.draggable.js)  worked for me on iPhone3 and iPhone6.

**Comment by rajkaran** [comment]
Hi Quazistax,

I tested this fork on iPhone5 and it works....  thanks a lot

**Comment by nolazybits** [comment]
FYI I have created a fork 
https://github.com/nolazybits/svg.draggable.js

and added a tag 0.1.1 which adds the touchevent from
https://github.com/bubenshchykov/svg.draggable.js

to the latest 0.1.0 code (i.e there is constraint as function feature)

**Comment by bubenshchykov** [comment]
anyone made a similar touch-fork which works with svg.js v2.0.1?

**Comment by IonicaBizau** [comment]
@bubenshchykov [`svg.draggy.js`](https://github.com/jillix/svg.draggy.js) works fine with touch events in Chrome mobile emulation. If you have any problems with it we are there to help you. :smile:

**Comment by bubenshchykov** [comment]
@IonicaBizau thanks man, giving it a try now :)

**Comment by bubenshchykov** [comment]
@IonicaBizau works like a charm! in Chrome emulation.. and even on Android :) but not on iphone/ipad yet :))) I might push a small PR to it soon. 

But god dammit, we should make it to svg.draggable.js. It's useless without touch support! 21st century )

**Comment by IonicaBizau** [comment]
@bubenshchykov Hehe, good to hear! If you fine any solution for iPhone/iPad, contributions are really welcome. :smile: 

We forked this project and renamed into `svg.draggy.js` to make it better. It was a time when this project was not really maintained. :grin:

**Comment by bubenshchykov** [comment]
@IonicaBizau lol it appears that I'm blind :D you draggy or something very similar was merged to svg.draggable.js master 2 days ago, as well as few more stability fixes!

So I made a PR with iPhone/iPad fix here https://github.com/wout/svg.draggable.js/pull/44

**Comment by IonicaBizau** [comment]
@bubenshchykov :+1:
