### ISSUE TITLE
option to drag using transform manipulation

### ISSUE THREAD

**Issue by blq** [wout/svg.draggable.js#3]
I think it would be nice to have an option to let the the dragging be performed by manipulating the object's actual transform matrix instead of the position. For setups where you use transforms this can be more consistent I'd say.
Or, more immediately obvious perhaps is that if you currently drag an object with a translation set you get a "double move jump" offset that could be considered a bug. 

Regards
/ Fredrik Blomqvist

**Comment by Fuzzyma** [comment]
This is fixed in the new version (except for groups which works only with translations - but dont drag a group - it cant be really considered as element but more as a container for elements)

Dragging is performed using the normal attributes. All others would be ridicolous.
