### ISSUE TITLE
JS error after setting fixed() when we have more than 1 draggable element

### ISSUE THREAD

**Issue by pjfsilva** [wout/svg.draggable.js#30]
Steps to reproduce:
1 - Go to http://pjfs.pt/svg/
2 - Open developer tools / javascript console and press the button "makefixed"
3 - click on a black circle on the map. A javascript error appears:
     Uncaught TypeError: Cannot read property 'bind' of null     svg.js:2074 
      SVG.onsvg.draggable.js:59 start

For multiple tests I can't understand the root cause of the problem but this only happens when I draw multiple circles on my SVG. When I only have 1 circle that is set as draggable(); the problem doesn't occur. 
For example try the same steps on this page that only has 1 circle: http://pjfs.pt/svg/1.html

It seems that calling draggable / fixed() multiple times causes some kind of event listener problem but I couldn't understand the root cause for it.

**Comment by Fuzzyma** [comment]
Is this still an issue with the new version?
