### ISSUE TITLE
How can I start dragging a shape directly after having created it?

### ISSUE THREAD

**Issue by opgobee** [wout/svg.draggable.js#31]
On mousedown on the document I create a shape, call draggable() on it, but then I don't succeed in starting the drag straight away, using the same mousedown event. I must release the mouse and then mousedown again on the shape to initiate the dragging.

I cannot call the start() method inside svg.draggable.js because it is connected to a private variable.
So I tried to trigger the mousedown event in svg.draggable.js, in several ways, but in vain. 

The only way I succeeded was by adding a line inside the original svg.draggable.js, which is ugly.
How to this without having to mess in the original svg.draggable.js?

I tried:
```javascript
// INFO: mousedown on document calls new HandlePoint(x,y,e), e= mousedown event

function HandlePoint(x,y,e)
{
    // create new svg circle with svg.js; 'svgCanvas' is the svg document in the html
    this.svgCircle = svgCanvas.circle(radius);
    //make the svg circle draggable, with svg.draggable.js
    this.svgCircle.draggable();
    
    // DOESN'T WORK: the created circle is not draggable straight away, 
    // i.e. the mousedown handler in draggable() is not directly called by the mousedown event that triggered the creation of the shape

    // DOESN'T WORK: directly evoking the mousedown explicitly after the draggable method has been attached 
    this.svgCircle.dispatchEvent(e); 

    // DOESN'T WORK: evoking a newly created mousedown event, uncoupling it from the thread by a timeout 
    this.svgCircle.triggerStart = function()
    {
	    var triggeredEvent = new MouseEvent('mousedown', {
	    	'view': window,
		    'bubbles': true,
		    'cancelable': true
	    });
	    this.dispatchEvent(triggeredEvent);	
    }
    setTimeout(this.svgCircle.triggerStart(),1);
   
    // THE ONLY THING THAT WORKS, BUT IS UGLY because it requires adapting the svg.draggable.js....
    this.svgCircle.draggable.triggerStart(e);
}

// ...REQUIRES ADDING THIS LINE inside svg.draggable.js to create a connection to the private start method...
	
        element.draggable.triggerStart = start
```

**Comment by Fuzzyma** [comment]
You have to dispatch the event on the node and not on the object which is only wrapped around the node.

    this.svgCircle.node.dispatchEvent(e); // That should work

**Comment by opgobee** [comment]
Thanks!
I got it working in some other way, but I’ll try this!
best wishes,
Paul

**Comment by Fuzzyma** [comment]
Did it work?

**Comment by opgobee** [comment]
Dear Wout,

thanks for coming back on this!

Unfortunately the development has been lying still for some time due to other work but we hope to be able to continue with it over the next weeks.
Your question reassures me that I can ask you in case I would have troubles getting it to work. Thanks!

Btw, just curious, 'Wout' sounds quite a Dutch name, are you Dutch?

best regards,
Paul Gobée
________________________________
Van: Fuzzy [notifications@github.com]
Verzonden: vrijdag 18 september 2015 18:12
Aan: wout/svg.draggable.js
CC: Gobee, O.P. (ANA)
Onderwerp: Re: [svg.draggable.js] How can I start dragging a shape directly after having created it? (#31)


Did it work?

**Comment by Fuzzyma** [comment]
I am sorry to disappoint you but thats not wout but me ;).
His githubprofile says spain.
However I really would like to know if this little change was the solution :)

**Comment by opgobee** [comment]
Actually I recall I had got it working, but only with a little change in the svg core (so not with Wout's solution). Something that one obviously doesn't want. This was after a lot of trying everything to prevent having to hack core (This solution was before Wout mailed his proposal for solving it). As it did work at that moment and Wout's solution came much later when I was working on other issues and I was not too sure that I would have overlooked an easy already present solution I think I didn't go into researching it again. But I might one day when I can get to work on it again.
Paul

________________________________
Van: Fuzzy [notifications@github.com]
Verzonden: zondag 20 september 2015 0:14
Aan: wout/svg.draggable.js
CC: Gobee, O.P. (ANA)
Onderwerp: Re: [svg.draggable.js] How can I start dragging a shape directly after having created it? (#31)


I am sorry to disappoint you but thats not wout but me ;).
His githubprofile says spain.
However I really would like to know if this little change was the solution :)

**Comment by Fuzzyma** [comment]
Actually it was my solution but nevermind ^^. Maybe I will just test it myself :)

**Comment by GuskiS** [comment]
I need this too. Can't seem to figure it out.

**Comment by Fuzzyma** [comment]
```javascript
var rect = draw.rect(100,100)
var e = new MouseEvent('mousedown', mouseEventInit)
rect.fire(e)
```

where `mouseEventInit` takes parameters from
- https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent
- https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/UIEvent
- https://developer.mozilla.org/en-US/docs/Web/API/Event/Event

**Comment by GuskiS** [comment]
The thing is, I'm setting .draggable already in `mousedown` event for that shape. When I create new MouseEvent, it gets in endless loop. If I move out .draggable and set in on create - I got issues with polylines and similir, when accidentaly clicking on drawed lines.

**Comment by Fuzzyma** [comment]
Show me your code please

2016-08-14 16:42 GMT+02:00 GuskiS <notifications@github.com>:

**Comment by GuskiS** [comment]
```
// Creating
self.shapeData.shape = buildShape().draw(e);
self.shapeData.shape.mousedown(selectShape);

function selectShape(e) {
  if(self.mouseData.type == 'select') {
    deselectShape();
    self.mouseData.selected = e.target.instance.selectize().resize().draggable();
    e.preventDefault();
  }
}
```
Something like this.

**Comment by Fuzzyma** [comment]
Why you make your shape draggable on mousedown? It will not be dragged anyway as long as you didnt click on it. You can make it draggable by default like

```javascript
self.shapeData.shape = buildShape().draw(e).draggable();
```

However: 
The more hidden way is to do this:

```javascript
// get the drag handler
var dragHandler = this.remember('_draggable') || new DragHandler(this)
// start the drag. event is the mousedown event
dragHandler.start(event)

**Comment by GuskiS** [comment]
Like I said, if I set .draggable() on create, poly- can get messed up because I can click on the line and move it before I have finished with poly- drawing.
I don't understand the later code of yours.

**Comment by Fuzzyma** [comment]
Edited it to be more specifig. rect is your element. the rest is just copy and pasting into your selectShape function after you called draggable.

**Comment by GuskiS** [comment]
Perfect, excatly what I needed. Except the `new DragHandler(this)` is not found outside your plugin if don't add .draggable() below:

```js
      function selectShape(e) {
        if(self.mouseData.type == 'select') {
          deselectShape();
          self.mouseData.selected = e.target.instance.selectize().resize().draggable();
          self.mouseData.selected.remember('_draggable').start(e);
        }
      }
```

**Comment by Fuzzyma** [comment]
right. I just saw this exactly before you commented. Ofc its not found. I edited again. Draghandler is set anyway because we called draggable before. We dont need to create a new one

**Comment by GuskiS** [comment]
You are best, thank you :) Your plugins are very well made and usefull for what I am doing.
Btw, while I'm writing this, I have problem with svg.draw, not sure if it is yours or svg.js itself:
```js
TypeError: this.value[1] is undefined            svg.js:531:7
```
This happens when I try to draw `line`.

**Comment by Fuzzyma** [comment]
Thank you :).
Mh cant say that without looking deeper into this. I would recommend debuging this (look at the stack trace first). Something is obviously wrong there.
If you find what causes this issue dont hesistate to open a new issue on the corresponding issue tracker.

**Comment by GuskiS** [comment]
When I do `draw.line()` it doesn't work and it doesn't call the svg.draw plugin (put some loggers). If I do `draw.line(0, 0)` it works as expected.

**Comment by Fuzzyma** [comment]
When you create a line without any argument, a default PointArray is generated which coniststs out of `[0,0]` which basically means `x1` and `y1` (while it means just the first point in Polygon or Polyline).
It then calls `toLine` to convert the PointArray to line-syntax (x1, x2, y1, y2). But this fails because we only have one point and not two.

The way you chose works more or less. You should get a few nulls in your html code.
The way to go is `line(0,0,0,0)`. That are valid line coordinates

**Comment by GuskiS** [comment]
Ok, I understand. Thank you. I just got used to that any other shape didn't need any params and they worked just fine.

**Comment by Fuzzyma** [comment]
jeah in this special case the default values arent doing any good :D. We
may have to doublecheck that...

2016-08-14 18:16 GMT+02:00 GuskiS <notifications@github.com>:
