### ISSUE TITLE
plugin throws 'this.parent._parent is not a function error' (crashes plugin)

### ISSUE THREAD

**Issue by bryan-gislason** [wout/svg.draggable.js#33]
I just start receiving this error, "this.parent._parent is not a function error". I'm on latest version of svg.js and svg.draggable.js.

You mentioned before about changing the line:
```
parent = this.parent._parent(SVG.Nested) || this.parent._parent(SVG.Doc);
```
in https://github.com/wout/svg.js/issues/214#issuecomment-46773204,  due to https://github.com/wout/svg.js/issues/214#issuecomment-46758391

to

```parent = this.parent(SVG.Nested) || this.parent(SVG.Doc)``` 

It seems to fix this bug. Want me to create a pull request?

**Comment by Fuzzyma** [comment]
If this plugin would have a dependency list it would be svg.js version 1.1.x ;) 

Maybe you saw the length of the PR-list. This plugin is written badly and i have to rewrite it Anyway. So no need for the PR. Just change it locally and wait for the rework :)

**Comment by bryan-gislason** [comment]
Sounds good. Thanks
