### ISSUE TITLE
Dragged elements become hidden behind other elements

### ISSUE THREAD

**Issue by gerrat** [wout/svg.draggable.js#36]
Title pretty much says it.

[Codepen example here](http://codepen.io/anon/pen/wapKMJ)
 - drag yellow circle and it becomes hidden.

Note: I copy/pasted the minified svj.js & svg.draggable.js right into the javascript, since I wanted to be sure to have the latest version.

Code is basically:

    var draw = SVG('drawing').size(300, 300)
    draw.circle(50,50,50).fill('yellow').move(120,120).draggable();
    draw.rect(100,100);

[The answer to this SO question may be useful](http://stackoverflow.com/questions/29212899/dragging-svg-element-over-another-svg-element)

Regards,
  Gerrat

**Comment by Fuzzyma** [comment]
That should be basic html-knowledge. Elements which comes later in the dom-tree are placed over the other elements.

Just call `rect.front()` before dragging. Maybe nicely using events:

```javascript
circle.on('beforedrag', function(){
  this.front()
})
```

**Comment by gerrat** [comment]
Well, I knew *why* it happens.  What I didn't know about was an easy way to get around it in this library (the `front()` method).  Sorry for the noise.
