### ISSUE TITLE
Some problems with draggable

### ISSUE THREAD

**Issue by ricardo85x** [wout/svg.draggable.js#37]
Hi

Follow the code https://jsfiddle.net/gnmobz34/4/

1 - On firefox/safari, When you click in the text it move to the left a bit. This problem arise when you use tex-anchor
2 - on jsfiddle, it do not work with google chrome.
3 - If you use the same code outside jsfiddle, it work on chrome, but the text.move(200,200), doesn't work

**Comment by dhardtke** [comment]
+1 I noticed the same when using the text-anchor attribute

**Comment by ricardo85x** [comment]
Hi.
Where is the new file?
I did tried with
https://raw.githubusercontent.com/wout/svg.draggable.js/2.1.3/src/svg.draggable.js
and
https://raw.githubusercontent.com/wout/svg.draggable.js/master/src/svg.draggable.js
And got the same problem.
Thanks

**Comment by Fuzzyma** [comment]
What exactly happens?

**Comment by ricardo85x** [comment]
https://jsfiddle.net/gnmobz34/4/

When you click in the element, it moves

**Comment by Fuzzyma** [comment]
not in my Browser (FF)

**Comment by ricardo85x** [comment]
Humm I see.
It only happen with firefox on Mac OS X.
I tried with firefox on Windows 10 and it does not happen.
Also it works ok on chrome and safari on Mac OS X.

I only have problem with Firefox on Mac OS X.
I tried Firefox 41,42,44

https://jsfiddle.net/gnmobz34/10/

**Comment by Fuzzyma** [comment]
well - thats something I cant debug and I wont because its a bug of this special browser.
They should fix it
