### ISSUE TITLE
add link to draggable group

### ISSUE THREAD

**Issue by fibo** [wout/svg.draggable.js#38]
Hi,

if I add a link to a draggable group, after dragend the link is open. See [this example](https://sherman-serpent.codio.io/gh-pages/_site/examples/synopsis.html).

I guess the right behaviour should be disable link on dragstart and enable it on dragend while clicking on the group should behave as a normal link.

I added link to group with [this code](https://github.com/fibo/flow-view/blob/master/src/Node.js#L58)

```
  if (typeof view.link === 'string')
    group.linkTo(view.link)
```

Any hint?

**Comment by Fuzzyma** [comment]
So you can do exatly this. Disable the link with `beforedrag` event and enable it after with `dragend` event. Nothing svg.draggable.js should care about :)
