### ISSUE TITLE
support for resize

### ISSUE THREAD

**Issue by rui-cruz** [wout/svg.draggable.js#42]
Hi,

Can you fork [svg.resize.js](https://github.com/Fuzzyma/svg.resize.js) and implement your touch events and create a pull request? ^^

Regards

**Comment by Fuzzyma** [comment]
you know that you are talking to the same person here? :D

**Comment by rui-cruz** [comment]
lol I thought it was other dev contribution! (so many repositories xD)

So in this case, can you help?

**Comment by Fuzzyma** [comment]
nope - but feel free to try it yourself :D

**Comment by rui-cruz** [comment]
Well soon or later I'll will have to.. I'm in the search of an svg lib that could be used on mobile, I like yours but I saw only one pull request for drag with touch. That's why I asked.
