### ISSUE TITLE
How can I dynamically constrain my Lines based on another Line?

### ISSUE THREAD

**Issue by stevenmybarra** [wout/svg.draggable.js#47]
I'm dynamically creating a number of lines, usually in pairs.

This code below creates my 2 lines.

```javascript
var draw = SVG('canvas').viewbox(0, 0, 2048, 512).size(2048, 512)

color = "#bf8f8f";
var lineX1_one = draw.line(5, 0, 5, 512).stroke({ width: 3, color:color }).style('cursor:move')
var lineX1_two = draw.line(1019, 0, 1019, 512).stroke({ width: 3, color:color }).style('cursor:move')

lineX1_one.draggable({	
	minX: 0, //0
	minY: 0,
	maxX: 2048,
	maxY: 512
})

lineX1_two.draggable({	
	minX: 0, //0
	minY: 0,
	maxX: 2048,
	maxY: 512
})
```

The two lines drag, but i want line 1 NOT TO PASS line 2, and vice versa.
Now, I did set my line1's maxY at 1018, and that works.

But I'm not sure how to make it work if line 2 is moved to the left, set at 50 pixels.

How can i make sure line 1 will only go up to 49?

I"m not sure how to read your dynamic constraints code:

```javascript
rect.draggable(function(x, y) {
  return { x: x < 1000, y: y < 300 }
})
```

**Comment by Fuzzyma** [comment]
The callback has x and y as parameters. You either just can return `true` or `false` to mark a movement as allowed or not (x < 1000 is boolean) or you can return a value where the element should be moved instead.

In your case you could check the position of the other line or something:
```javascript 
lineX1_one.draggable(function(x,y){
    var x_allowed = x < lineX1_two.x()
    var y_allowed = y < lineX1_two.y()
    return { x: x_allowed, y: y_allowed };
})
```

**Comment by stevenmybarra** [comment]
Thanks for the quick reply!, I got it working by your suggestion!
