### ISSUE TITLE
Support for delay to drag element

### ISSUE THREAD

**Issue by radabass** [wout/svg.draggable.js#51]
Hi,
This is an issue regarding mobile devices, when a user wants to scroll a page filled with a draggable SVG it requires the event (and the e.preventDefault() of course) to be delayed for a time (as a parameter if possible) so this way:
1- A user may scroll on the screen if the touch lasts for less than the delay.
2- If the touch over the element lasts longer the user may drag the element as usual.

Other solutions to allow the user to scroll the page if the SVG file fills all the window are welcome (on mobile devices) if you think any other solution please comment this issue.

Thank you!

**Comment by Fuzzyma** [comment]
Hey, interesting thoughts. Unfortunately you cant prevent a scroll from happen within in a few milliseconds. whenever an element is dragged, it calls `preventDefault()` to prevent the custom behavior from happening (in your case scrolling). If you dont do that immediately it doesnt work.

Imo the responsibility of this problems lays by the programmmer. e.g. you can disable the draggable functionality whenever a scroll could happen next or you can allow the drag only on doubleclick.
Be creative - I myself cant think about a solution which would be build in.

**Comment by radabass** [comment]
/* External code must be used to achieve scroll on mobile devices */
