### ISSUE TITLE
Dragging a group doesn't updates children's center

### ISSUE THREAD

**Issue by ferdas** [wout/svg.draggable.js#53]
Hello everyone!

I'm writing here to know whether this behaviour is intender or not:
If I create a group of elements and I drag it around it won't update the children's centres ( retrieved by cx() and cy() ).

Here's a demo: http://codepen.io/anon/pen/QyNoXm#0

Please, let me know if a fix is needed, I could do it (maybe ^^") and then raise a pull request :)

Have a nice day,
Francesco

**Comment by ferdas** [comment]
After further investigation I've concluded that, even in this way, the behaviour can be an acceptable interpretation of the SVG specs [1].

I guess that, in my case, I should handle the calculus against the CTM by myself.

Thank you anyway and have a nice day :)

[1] [Mozilla's MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g)

**Comment by Fuzzyma** [comment]
Hey @ferdas 
svg.js always "tries" to return the values of an element in user space (say: the elements coordinate system). A group for example creates a new user space in which the elements life.
Thats why the element is positioned relative to the group.
So yes - as you said: This is intended :)

**Comment by ferdas** [comment]
Thank you for your explanation @Fuzzyma! :)
