### ISSUE TITLE
Drag offset resets with svg.ForeignObject

### ISSUE THREAD

**Issue by adamlwgriffiths** [wout/svg.draggable.js#54]
I've found that dragging an svg.ForeignObject causes subsequent drags to move the object back to its initial position as dragging commences.

Ie, object starts at [A], drag to [B].
When I next click on the object at [B], it immediately jumps to [A] and becomes offset from the mouse - albeit still responding to the drag event.

Example code is below, script paths will need to be updated to actual paths relevant for you / CDN urls.

```
<html>
<head>
<script type="text/javascript" src="../../static/svgjs/svg.js"></script>
<script type="text/javascript" src="../../static/svgjs/svg.connectable.js"></script>
<script type="text/javascript" src="../../static/svgjs/svg.draggable.js"></script>
<script type="text/javascript" src="../../static/svgjs/svg.draggy.js"></script>
<script type="text/javascript" src="../../static/svgjs/svg.foreignobject.js"></script>
</head>

<body>
<div id="drawing"></div>

<script>
//var draw = SVG('drawing').size(800, 600);
var svg = new SVG(document.querySelector("#drawing")).size("100%", 500);
var links = svg.group();
var markers = svg.group();
var nodes = svg.group();

var g1 = nodes.group().translate(300, 200).draggy(function(x,y){
    if(x < 10) {
        return false;
    }
    return true;
});
g1.circle(80).fill("#C2185B");

var g2 = nodes.group().translate(100, 200).draggy();
g2.circle(50).fill("#E91E63");

var g3 = nodes.group().translate(200, 400).draggy();
g3.circle(100).fill("#FF5252");

g1.connectable({
    container: links,
    markers: markers
}, g2).setLineColor("#5D4037");

g2.connectable({
    padEllipse: true
}, g3).setLineColor("#5D4037")




var fobj = svg.foreignObject(100,100).attr({id: 'fobj'});
var txt = "some text that is quite long.  and it goes on and on.  and it's pointless really.  and the grammar is terrible.  blah. blah. blah";

fobj.appendChild("div", {id: 'mydiv', innerText: txt})
var n = fobj.getChild(0)
fobj.attr({width: 200, height: 100}).rotate(45)//.move(100,0)
n.style.height = '50px'
n.style.overflow = 'hidden'
n.style.border = "solid black 1px"

fobj.draggy();

</script>
</body>
</html>

```

**Comment by adamlwgriffiths** [comment]
Sorry wrong repository.

**Comment by adamlwgriffiths** [comment]
Actually, occurs with both svg.draggy and svg.draggable.
Any insight would be appreciated.

**Comment by Fuzzyma** [comment]
Please create a jsfiddle for this problem. You can't expect that everyone
reviewing this issue will adapt your code for testing. Also you could try
to modify your code to the core problem. That would help very much!

Adam Griffiths <notifications@github.com> schrieb am Do., 11.02.2016, 6:44:

**Comment by adamlwgriffiths** [comment]
It's literally the `svg.ForeignObject` example code with `draggable` called on it.

https://jsfiddle.net/6zrqy7h4/

**Comment by Fuzzyma** [comment]
Thanks I will look into it as soon as I find the time

**Comment by Fuzzyma** [comment]
Mh - thats an odd problem. Firefox drags the object correctly but doenst display the text (it seems the code doesnt work in FF because when you add the text manually it works).
Chrome displays the text but fails the drag.
Not sure on how to continue here...

**Comment by adamlwgriffiths** [comment]
Sounds like ForeignObject is relying on non-standardised behaviour.
Considering other objects seem to work, I don't think it's your library.
Thanks for taking a look though =)

**Comment by rudevich** [comment]
seems it fixed by adding to svg.draggy.js#47 condition:
`} else if (element instanceof SVG.Nested || element instanceof SVG.Shape) {`

**Comment by Fuzzyma** [comment]
@rudevich in all browsers?

**Comment by rudevich** [comment]
@Fuzzyma Sorry! It was about svg.draggy (was opened in other tab) https://github.com/jillix/svg.draggy.js/blob/master/src/svg.draggy.js
But I thing in svg.draggable there is something similar (type checking)

**Comment by Fuzzyma** [comment]
Might you test?
