### ISSUE TITLE
plugin supported/up-to-date?

### ISSUE THREAD

**Issue by LordNavro** [wout/svg.draggable.js#55]
I am working on an SVG project and would love to make use of svg.js libraries.

However, the method mentioned in README does not work. I have
```
	<script  src="plugins/svg.js" type="text/javascript"></script>
	<script  src="plugins/svg.draggable.js" type="text/javascript"></script>
```
and when i try
```
	svg = SVG("printAreaFrame");
	var rect = svg.rect(100, 100);
	rect.draggable();
```
i get Uncaught TypeError: rect.draggable is not a function. The svg.js itself seems to work well, tho.

Is this script still compatible with current svg.js?
Also, svgjs.com doesnt seem to work properly (some troubles with linked resources, as far as i can tell).

**Comment by Fuzzyma** [comment]
Thats the third time someone reports an error about this plugin not working and a few hours later they fix it itself but noone wants to say what there mistake was.
I always try it myself and it always works...

to cut a long story short: I cant reproduce it. Which Browser? Which svg version (maybe exact commit), which draggable version?

**Comment by LordNavro** [comment]
Alright, finally found the error, it was my stupid fault.

I found an extra script linking svg.js again after the draggable plugin was loaded. I assume this has rewritten the SVG object and thus removed the extension. It might be convenient to produce some warning or so when svg.js was already loaded, but as i am not a pro js developer, I dont know how are these things treated in general and its a topic for another repo.

Anyway, it still might be beneficial to update svgjs.com, it contains some obsolete info, and the examples (such as http://svgjs.com/clock/ ) do not work.

Thank you for your help anyway.

**Comment by Fuzzyma** [comment]
I have no access to the site so I cannot change the current status.
Dependency management is stuff of the user. He has to make sure, that every script loads correctly. Nothing the lib should care about!
