### ISSUE TITLE
Doc change: warn about transitions

### ISSUE THREAD

**Issue by SeanHayes** [wout/svg.draggable.js#56]
I was having problems with element movements being delayed. After looking at a few possible problems I realized CSS transitions were being applied from elsewhere in our code, which was causing the delayed response.

I thought it might be helpful to add a warning to the README reminding people to disable CSS transitions for draggable elements.

BTW, here's how I selectively disabled transitions only during drag:

    /* from: http://stackoverflow.com/a/16575811/241955 */
    .notransition {
      -webkit-transition: none !important;
      -moz-transition: none !important;
      -o-transition: none !important;
      -ms-transition: none !important;
      transition: none !important;
    }

    function disableTransitions(){
        this.addClass('notransition');
    }
    function allowTransitions(){
        this.removeClass('notransition');
    }

    el.on('dragstart', disableTransitions);
    el.on('dragend', allowTransitions);

**Comment by Fuzzyma** [comment]
Feel free to add this to the docs yourself. Imo thats not the plugins fault but a warning wont hurt i guess
