### ISSUE TITLE
problem with attribute 

### ISSUE THREAD

**Issue by AletisFirst** [wout/svg.draggable.js#57]
In old version of plugin, I can secure the X position of blue circle. Look at code:

// svg.js v.1.1.1
// svg.draggable.js v.0.1.0 
    var svg = SVG('canvas').size(canvas.width, canvas.height);
    var blueCircle = svg.circle(44).cx(100).cy(100).fill('blue').draggable();
    var redCircle = svg.circle(22).cx(150).cy(100).fill('red').draggable();
    var old_cx;
    blueCircle.beforedrag = function () {
        old_cx = blueCircle.attr('cx');
    };
    blueCircle.dragmove = function () {
        blueCircle.cx(old_cx);  // It works!
        redCircle.cy(blueCircle.attr('cy'));
    };

In new version of plugin, I can't secure the X position of blue circle. Look at code:
// svg.js v.2.3.0
// svg.draggable.js v.2.3.1 
    var svg = SVG('canvas').size(canvas.width, canvas.height);
    var blueCircle = svg.circle(44).cx(100).cy(100).fill('blue').draggable();
    var redCircle = svg.circle(22).cx(150).cy(100).fill('red').draggable();
    var old_cx;
    blueCircle.on('beforedrag', function () {
        old_cx = blueCircle.attr('cx');
    });
    blueCircle.on('dragmove', function () {
        blueCircle.cx(old_cx); // It does not work!
        redCircle.cy(blueCircle.attr('cy'));
    });

What is the problem?

**Comment by Fuzzyma** [comment]
This should be fixed in 2.2.0. You can now prevent the default action and do your own stuff instead.
https://github.com/wout/svg.draggable.js#eventpreventdefault
