### ISSUE TITLE
will custom drag action feature in the coming version?

### ISSUE THREAD

**Issue by CyrusNG** [wout/svg.draggable.js#58]
May I known whether it has custom drag action feature that only send drag event without any svg change in the coming version?

**Comment by Fuzzyma** [comment]
Added with new v2.2.0. You can call `preventDefault` in the callback handler of `dragmove` and realize your own behavior. See docs for more details:
https://github.com/wout/svg.draggable.js#eventpreventdefault

**Comment by CyrusNG** [comment]
Thank you.
