### ISSUE TITLE
Snap to grid

### ISSUE THREAD

**Issue by jkevingutierrez** [wout/svg.draggable.js#60]
Hi everyone !

I think that would be great to allow the snap to grid. Something like the people of svg.resize.js do: http://fuzzyma.github.io/svg.resize.js/demo/index.html

**Comment by Fuzzyma** [comment]
You can use teh constraint feature for this. Just pass a function which returns the snapped values e.g.
```javascript
rect.draggable(function(x, y){
    return {
        x: x - x % gridSize,
        y: y - y % gridSize
    };
});
```

That question actually was already asked so pls use the search first: #11

**Comment by jkevingutierrez** [comment]
Thanks man ! Excuse me !
